### ISSUE TITLE
does not compile on io.js

### ISSUE THREAD

**Issue by timoxley** [mcavage/node-bunyan-syslog#15]
```
> bunyan-syslog@0.2.2 install /…/bunyan-syslog
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/syslog/src/syslog.o
../src/syslog.cc:57:26: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
Handle<Value> Open(const Arguments& args) {
                         ^~~~~~~~~
                         v8::internal::Arguments
/Users/timoxley/.node-gyp/1.1.0/deps/v8/include/v8.h:133:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/syslog.cc:58:14: error: calling a protected constructor of class 'v8::HandleScope'
        HandleScope scope;
                    ^
/Users/timoxley/.node-gyp/1.1.0/deps/v8/include/v8.h:878:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/syslog.cc:60:2: error: member access into incomplete type 'const v8::internal::Arguments'
        REQUIRE_STRING_ARG(args, 0, ident);
        ^
../src/syslog.cc:34:2: note: expanded from macro 'REQUIRE_STRING_ARG'
        REQUIRE_ARGS(ARGS);                                             \
        ^
../src/syslog.cc:23:10: note: expanded from macro 'REQUIRE_ARGS'
        if (ARGS.Length() == 0)                                 \
                ^
/Users/timoxley/.node-gyp/1.1.0/deps/v8/include/v8.h:133:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../src/syslog.cc:60:2: error: no member named 'New' in 'v8::String'
        REQUIRE_STRING_ARG(args, 0, ident);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/syslog.cc:34:2: note: expanded from macro 'REQUIRE_STRING_ARG'
        REQUIRE_ARGS(ARGS);                                             \
        ^~~~~~~~~~~~~~~~~~
../src/syslog.cc:24:3: note: expanded from macro 'REQUIRE_ARGS'
                RETURN_ARGS_EXCEPTION("missing arguments");
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/syslog.cc:14:53: note: expanded from macro 'RETURN_ARGS_EXCEPTION'
        return ThrowException(Exception::TypeError(String::New(MSG)))
                                                   ~~~~~~~~^
../src/syslog.cc:60:2: error: member access into incomplete type 'const v8::internal::Arguments'
../src/syslog.cc:35:10: note: expanded from macro 'REQUIRE_STRING_ARG'
        if (ARGS.Length() <= (I) || !ARGS[I]->IsString())               \
                ^
/Users/timoxley/.node-gyp/1.1.0/deps/v8/include/v8.h:133:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../src/syslog.cc:60:2: error: no member named 'New' in 'v8::String'
        REQUIRE_STRING_ARG(args, 0, ident);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/syslog.cc:36:3: note: expanded from macro 'REQUIRE_STRING_ARG'
                RETURN_ARGS_EXCEPTION("argument " #I " must be a String"); \
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/syslog.cc:14:53: note: expanded from macro 'RETURN_ARGS_EXCEPTION'
        return ThrowException(Exception::TypeError(String::New(MSG)))
                                                   ~~~~~~~~^
../src/syslog.cc:60:2: error: type 'const v8::internal::Arguments' does not provide a subscript operator
        REQUIRE_STRING_ARG(args, 0, ident);
        ^                  ~~~~  ~
../src/syslog.cc:37:28: note: expanded from macro 'REQUIRE_STRING_ARG'
        String::Utf8Value VAR(ARGS[I]->ToString());
                                  ^
../src/syslog.cc:61:2: error: member access into incomplete type 'const v8::internal::Arguments'
        REQUIRE_INT_ARG(args, 1, logopt);
        ^
../src/syslog.cc:27:2: note: expanded from macro 'REQUIRE_INT_ARG'
        REQUIRE_ARGS(ARGS);                                             \
        ^
../src/syslog.cc:23:10: note: expanded from macro 'REQUIRE_ARGS'
        if (ARGS.Length() == 0)                                 \
                ^
/Users/timoxley/.node-gyp/1.1.0/deps/v8/include/v8.h:133:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../src/syslog.cc:61:2: error: no member named 'New' in 'v8::String'
        REQUIRE_INT_ARG(args, 1, logopt);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/syslog.cc:27:2: note: expanded from macro 'REQUIRE_INT_ARG'
        REQUIRE_ARGS(ARGS);                                             \
        ^~~~~~~~~~~~~~~~~~
../src/syslog.cc:24:3: note: expanded from macro 'REQUIRE_ARGS'
                RETURN_ARGS_EXCEPTION("missing arguments");
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/syslog.cc:14:53: note: expanded from macro 'RETURN_ARGS_EXCEPTION'
        return ThrowException(Exception::TypeError(String::New(MSG)))
                                                   ~~~~~~~~^
../src/syslog.cc:61:2: error: member access into incomplete type 'const v8::internal::Arguments'
../src/syslog.cc:28:10: note: expanded from macro 'REQUIRE_INT_ARG'
        if (ARGS.Length() <= (I) || !ARGS[I]->IsNumber())               \
                ^
/Users/timoxley/.node-gyp/1.1.0/deps/v8/include/v8.h:133:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../src/syslog.cc:61:2: error: no member named 'New' in 'v8::String'
        REQUIRE_INT_ARG(args, 1, logopt);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/syslog.cc:29:3: note: expanded from macro 'REQUIRE_INT_ARG'
                RETURN_ARGS_EXCEPTION("argument " #I " must be an Integer"); \
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/syslog.cc:14:53: note: expanded from macro 'RETURN_ARGS_EXCEPTION'
        return ThrowException(Exception::TypeError(String::New(MSG)))
                                                   ~~~~~~~~^
../src/syslog.cc:61:2: error: type 'const v8::internal::Arguments' does not provide a subscript operator
        REQUIRE_INT_ARG(args, 1, logopt);
        ^               ~~~~  ~
../src/syslog.cc:30:30: note: expanded from macro 'REQUIRE_INT_ARG'
        Local<Integer> _ ## VAR(ARGS[I]->ToInteger());                  \
                                    ^
../src/syslog.cc:62:2: error: member access into incomplete type 'const v8::internal::Arguments'
        REQUIRE_INT_ARG(args, 2, facility);
        ^
../src/syslog.cc:27:2: note: expanded from macro 'REQUIRE_INT_ARG'
        REQUIRE_ARGS(ARGS);                                             \
        ^
../src/syslog.cc:23:10: note: expanded from macro 'REQUIRE_ARGS'
        if (ARGS.Length() == 0)                                 \
                ^
/Users/timoxley/.node-gyp/1.1.0/deps/v8/include/v8.h:133:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../src/syslog.cc:62:2: error: no member named 'New' in 'v8::String'
        REQUIRE_INT_ARG(args, 2, facility);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/syslog.cc:27:2: note: expanded from macro 'REQUIRE_INT_ARG'
        REQUIRE_ARGS(ARGS);                                             \
        ^~~~~~~~~~~~~~~~~~
../src/syslog.cc:24:3: note: expanded from macro 'REQUIRE_ARGS'
                RETURN_ARGS_EXCEPTION("missing arguments");
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/syslog.cc:14:53: note: expanded from macro 'RETURN_ARGS_EXCEPTION'
        return ThrowException(Exception::TypeError(String::New(MSG)))
                                                   ~~~~~~~~^
../src/syslog.cc:62:2: error: member access into incomplete type 'const v8::internal::Arguments'
../src/syslog.cc:28:10: note: expanded from macro 'REQUIRE_INT_ARG'
        if (ARGS.Length() <= (I) || !ARGS[I]->IsNumber())               \
                ^
/Users/timoxley/.node-gyp/1.1.0/deps/v8/include/v8.h:133:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../src/syslog.cc:62:2: error: no member named 'New' in 'v8::String'
        REQUIRE_INT_ARG(args, 2, facility);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/syslog.cc:29:3: note: expanded from macro 'REQUIRE_INT_ARG'
                RETURN_ARGS_EXCEPTION("argument " #I " must be an Integer"); \
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/syslog.cc:14:53: note: expanded from macro 'RETURN_ARGS_EXCEPTION'
        return ThrowException(Exception::TypeError(String::New(MSG)))
                                                   ~~~~~~~~^
../src/syslog.cc:62:2: error: type 'const v8::internal::Arguments' does not provide a subscript operator
        REQUIRE_INT_ARG(args, 2, facility);
        ^               ~~~~  ~
../src/syslog.cc:30:30: note: expanded from macro 'REQUIRE_INT_ARG'
        Local<Integer> _ ## VAR(ARGS[I]->ToInteger());                  \
                                    ^
../src/syslog.cc:66:10: error: no matching function for call to 'Undefined'
        return (Undefined());
                ^~~~~~~~~
/Users/timoxley/.node-gyp/1.1.0/deps/v8/include/v8.h:323:28: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
  friend Handle<Primitive> Undefined(Isolate* isolate);
                           ^
../src/syslog.cc:70:25: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
Handle<Value> Log(const Arguments& args) {
                        ^~~~~~~~~
                        v8::internal::Arguments
/Users/timoxley/.node-gyp/1.1.0/deps/v8/include/v8.h:133:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/syslog/src/syslog.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:100:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1040:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /…/bunyan-syslog
gyp ERR! node -v v1.1.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok

npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "rebuild"
npm ERR! node v1.1.0
npm ERR! npm  v2.4.1
npm ERR! code ELIFECYCLE
npm ERR! bunyan-syslog@0.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bunyan-syslog@0.2.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bunyan-syslog package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bunyan-syslog
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /…/npm-debug.log
```

https://github.com/iojs/io.js/issues/456

**Comment by cblanc** [comment]
Thank you!

**Comment by rimunroe** [comment]
I am still experiencing build errors in iojs v3.2.0.

```
$ npm install bunyan-syslog
-
> bunyan-syslog@0.3.0 install /Users/rimunroe/tmp/node_modules/bunyan-syslog
> node-gyp rebuild

  CXX(target) Release/obj.target/syslog/src/syslog.o
In file included from ../src/syslog.cc:7:
In file included from ../node_modules/nan/nan.h:74:
In file included from ../node_modules/nan/nan_new.h:190:
../node_modules/nan/nan_implementation_12_inl.h:181:66: error: too many arguments to function call, expected at most 2, have 4
  return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
         ~~~~~~~~~~~~~~~~~~                                      ^~~~~~~~~~
/Users/rimunroe/.node-gyp/3.2.0/include/node/v8.h:4450:3: note: 'New' declared here
  static Local<Signature> New(
  ^
In file included from ../src/syslog.cc:7:
../node_modules/nan/nan.h:165:25: error: redefinition of '_NanEnsureLocal'
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../node_modules/nan/nan.h:160:25: note: previous definition is here
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                        ^
../node_modules/nan/nan.h:310:12: error: no matching function for call to '_NanEnsureLocal'
    return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:296:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                                          ^~~~~~~~~~~~~~~
../node_modules/nan/nan.h:165:25: note: candidate template ignored: substitution failure [with T = v8::Primitive]
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../node_modules/nan/nan.h:315:12: error: no matching function for call to '_NanEnsureLocal'
    return NanEscapeScope(NanNew(v8::Null(v8::Isolate::GetCurrent())));
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:296:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                                          ^~~~~~~~~~~~~~~
../node_modules/nan/nan.h:165:25: note: candidate template ignored: substitution failure [with T = v8::Primitive]
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../node_modules/nan/nan.h:320:12: error: no matching function for call to '_NanEnsureLocal'
    return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:296:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                                          ^~~~~~~~~~~~~~~
../node_modules/nan/nan.h:165:25: note: candidate template ignored: substitution failure [with T = v8::Boolean]
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../node_modules/nan/nan.h:325:12: error: no matching function for call to '_NanEnsureLocal'
    return NanEscapeScope(NanNew(v8::False(v8::Isolate::GetCurrent())));
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:296:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                                          ^~~~~~~~~~~~~~~
../node_modules/nan/nan.h:165:25: note: candidate template ignored: substitution failure [with T = v8::Boolean]
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../node_modules/nan/nan.h:557:13: error: no member named 'smalloc' in namespace 'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../node_modules/nan/nan.h:568:12: error: no matching function for call to 'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
           ^~~~~~~~~~~~~~~~~
/Users/rimunroe/.node-gyp/3.2.0/include/node/node_buffer.h:31:40: note: candidate function not viable: no known conversion from 'uint32_t' (aka 'unsigned int') to 'enum encoding' for 3rd argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/rimunroe/.node-gyp/3.2.0/include/node/node_buffer.h:43:40: note: candidate function not viable: 2nd argument ('const char *') would lose const qualifier
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/rimunroe/.node-gyp/3.2.0/include/node/node_buffer.h:28:40: note: candidate function not viable: requires 2 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                       ^
/Users/rimunroe/.node-gyp/3.2.0/include/node/node_buffer.h:36:40: note: candidate function not viable: requires 5 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
In file included from ../src/syslog.cc:7:
../node_modules/nan/nan.h:572:12: error: no viable conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>'
    return node::Buffer::New(v8::Isolate::GetCurrent(), size);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/rimunroe/.node-gyp/3.2.0/include/node/v8.h:210:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object> &' for 1st argument
class Local {
      ^
/Users/rimunroe/.node-gyp/3.2.0/include/node/v8.h:210:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object> &&' for 1st argument
class Local {
      ^
/Users/rimunroe/.node-gyp/3.2.0/include/node/v8.h:214:13: note: candidate template ignored: could not match 'Local' against 'MaybeLocal'
  V8_INLINE Local(Local<S> that)
            ^
/Users/rimunroe/.node-gyp/3.2.0/include/node/v8.h:327:13: note: candidate template ignored: could not match 'S *' against 'v8::MaybeLocal<v8::Object>'
  V8_INLINE Local(S* that)
            ^
In file included from ../src/syslog.cc:7:
../node_modules/nan/nan.h:579:26: error: no member named 'Use' in namespace 'node::Buffer'
    return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
           ~~~~~~~~~~~~~~^
../node_modules/nan/nan.h:1396:12: error: no matching function for call to '_NanEnsureLocal'
    return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:296:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                                          ^~~~~~~~~~~~~~~
../node_modules/nan/nan.h:165:25: note: candidate template ignored: substitution failure [with T = v8::Function]
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../node_modules/nan/nan.h:1411:12: error: no matching function for call to '_NanEnsureLocal'
    return NanEscapeScope(node::MakeCallback(
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:296:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                                          ^~~~~~~~~~~~~~~
../node_modules/nan/nan.h:165:25: note: candidate template ignored: substitution failure [with T = v8::Value]
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../node_modules/nan/nan.h:1484:12: error: no matching function for call to '_NanEnsureLocal'
    return NanEscapeScope(handle->Get(NanNew(key)).As<v8::Object>());
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:296:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                                          ^~~~~~~~~~~~~~~
../node_modules/nan/nan.h:165:25: note: candidate template ignored: substitution failure [with T = v8::Object]
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../src/syslog.cc:95:17: error: no matching function for call to '_NanEnsureLocal'
        NanReturnValue(NanEscapeScope(NanNew<Integer>(mask)));
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:296:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                                          ^~~~~~~~~~~~~~~
../node_modules/nan/nan.h:299:65: note: expanded from macro 'NanReturnValue'
# define NanReturnValue(value) return args.GetReturnValue().Set(value)
                                                                ^
../node_modules/nan/nan.h:165:25: note: candidate template ignored: substitution failure [with T = v8::Integer]
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
14 errors generated.
make: *** [Release/obj.target/syslog/src/syslog.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/rimunroe/.nvm/versions/io.js/v3.2.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/Users/rimunroe/.nvm/versions/io.js/v3.2.0/bin/iojs" "/Users/rimunroe/.nvm/versions/io.js/v3.2.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/rimunroe/tmp/node_modules/bunyan-syslog
gyp ERR! node -v v3.2.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/rimunroe/.nvm/versions/io.js/v3.2.0/bin/iojs" "/Users/rimunroe/.nvm/versions/io.js/v3.2.0/bin/npm" "install" "bunyan-syslog"
npm ERR! node v3.2.0
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! bunyan-syslog@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bunyan-syslog@0.3.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bunyan-syslog package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bunyan-syslog
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rimunroe/tmp/npm-debug.log
```
